### ISSUE TITLE
MacOs :  StdoutException

### ISSUE THREAD

**Issue by rohitsangwan01** [RohitEdathil/ConsoleBars#3]
Getting  , Unhandled Exception: StdoutException: Could not get terminal size, OS Error: Inappropriate ioctl for device, errno = 25
on Macos M1

**Comment by RohitEdathil** [comment]
[This](https://stackoverflow.com/questions/63345739/ioerror-errno-25-inappropriate-ioctl-for-device#:~:text=Most%20IDE's%20like%20PyCharm%20or,Simulated%20Terminal%20inside%20a%20IDE.) might be the cause.

May I know which terminal are you trying to use this in?
The progress bar needs to know the width of the terminal. But when it tries to do this in an Simulated terminal like that of one inside an IDE, something goes wrong.

**Comment by RohitEdathil** [comment]
Running the code inside the OS's native terminal will most likely work for you.

**Comment by rohitsangwan01** [comment]
Ohh i see , i was using in Mac Vscode Terminal

**Comment by RohitEdathil** [comment]
I just tried to do it in my Windows VScode terminal and in worked!!
Maybe its an issue for the Mac version only?

I can add an extra parameter `width` to manually set the width of the progress bar to accommodate such cases.

**Comment by RohitEdathil** [comment]
Hey @rohitsangwan01 I have published a new version with the promised `width` parameter. This may fix your issue. I don't have a Mac with me, so can you try it out now after upgrading to 1.0.4 of the package and see if it works?

If it didn't work, feel free to let me know and I will work out a solution.

**Comment by rohitsangwan01** [comment]
@RohitEdathil  , thanks for update , but still not working , and if we pass width then flutter App hangs out , 
can you try with a flutter App , run that app in debug console in Vscode , and try to run then in your vscode

**Comment by RohitEdathil** [comment]
Its actually not designed to be used in a flutter app, but for desktop utilities and CLIs. 
When you want to show progress to a user in an app it doesn't make much sense to use console based progress bars.

I am guessing that you are using it to know the progress of a long running operation, just while the app is in development.
Giving some kind of a visual indicator in the UI would be a far better choice in that case. 

If you want it so badly, then trying with `time` as false may help.

And If you can give me a good enough reason to use it in a flutter app, I can invest a significant amount of time to try to make it work.

**Comment by rohitsangwan01** [comment]
@RohitEdathil  yeah exactly ,am  working on a bluetooth related app for different Platforms , in which i have to run few tests for long time , so this was just to get  a visual indicator in console for tasks running in background, but anyway its fine ,its not that much important , i can run those on UI for debugging
Thanks for your Efforts

**Comment by RohitEdathil** [comment]
```dart
final rate = clock.elapsedMicroseconds / (current == 0 ? 1 : current);
final eta = Duration(microseconds: ((total - current) * rate).toInt());
```
@rohitsangwan01,
If you just want to calculate the ETA, this piece of code which I used might come in handy.
Here,
- `total` : Total number of steps
- `current` : The step we are at
- `clock` : An instance of [Stopwatch](https://api.dart.dev/stable/2.15.1/dart-core/Stopwatch-class.html) object.

Hope this helps 😃
I am closing this issue now.

**Comment by rohitsangwan01** [comment]
@RohitEdathil  yeah am using something similar , thanks
